version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - '../www:/var/www/html'
      - './nginx/conf.d:/etc/nginx/conf.d'

  php:
    build:
       context: './php-fpm'
       args:
         INSTALL_XDEBUG: ${INSTALL_XDEBUG}
    volumes:
      - '../www:/var/www/html'

  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
